# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from ..types import Result, Ok, Err, Some


class Tools(Protocol):

    @abstractmethod
    def combinations(self, iterable: List[str], r: int) -> List[List[str]]:
        """
        TODO: use variant to support u32?
        TODO: tuple is better?
        """
        raise NotImplementedError

    @abstractmethod
    def permutations(self, iterable: List[str], r: int) -> List[List[str]]:
        raise NotImplementedError


