// Code generated by wit-bindgen-go. DO NOT EDIT.

package template

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "iter-tpl:tpl@0.0.1".

//go:wasmexport iter-tpl:tpl/template@0.0.1#execute
//export iter-tpl:tpl/template@0.0.1#execute
func wasmexport_Execute(tpl0 *uint8, tpl1 uint32, array0 *string, array1 uint32) (result *cm.Result[string, string, string]) {
	tpl := cm.LiftString[string]((*uint8)(tpl0), (uint32)(tpl1))
	array := cm.LiftList[cm.List[string]]((*string)(array0), (uint32)(array1))
	result_ := Exports.Execute(tpl, array)
	result = &result_
	return
}
