// Code generated by wit-bindgen-go. DO NOT EDIT.

package template

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "iter-tpl:tpl/template@0.0.1".
var Exports struct {
	// Execute represents the caller-defined, exported function "execute".
	//
	//	execute: func(tpl: string, array: list<string>) -> result<string, string>
	Execute func(tpl string, array cm.List[string]) (result cm.Result[string, string, string])
}
