// world root:component/root
export type * as WasiCliEnvironment020 from './interfaces/wasi-cli-environment.js'; // import wasi:cli/environment@0.2.0
export type * as WasiCliExit020 from './interfaces/wasi-cli-exit.js'; // import wasi:cli/exit@0.2.0
export type * as WasiCliStderr020 from './interfaces/wasi-cli-stderr.js'; // import wasi:cli/stderr@0.2.0
export type * as WasiCliStdin020 from './interfaces/wasi-cli-stdin.js'; // import wasi:cli/stdin@0.2.0
export type * as WasiCliStdout020 from './interfaces/wasi-cli-stdout.js'; // import wasi:cli/stdout@0.2.0
export type * as WasiCliTerminalInput020 from './interfaces/wasi-cli-terminal-input.js'; // import wasi:cli/terminal-input@0.2.0
export type * as WasiCliTerminalOutput020 from './interfaces/wasi-cli-terminal-output.js'; // import wasi:cli/terminal-output@0.2.0
export type * as WasiCliTerminalStderr020 from './interfaces/wasi-cli-terminal-stderr.js'; // import wasi:cli/terminal-stderr@0.2.0
export type * as WasiCliTerminalStdin020 from './interfaces/wasi-cli-terminal-stdin.js'; // import wasi:cli/terminal-stdin@0.2.0
export type * as WasiCliTerminalStdout020 from './interfaces/wasi-cli-terminal-stdout.js'; // import wasi:cli/terminal-stdout@0.2.0
export type * as WasiClocksMonotonicClock020 from './interfaces/wasi-clocks-monotonic-clock.js'; // import wasi:clocks/monotonic-clock@0.2.0
export type * as WasiClocksWallClock020 from './interfaces/wasi-clocks-wall-clock.js'; // import wasi:clocks/wall-clock@0.2.0
export type * as WasiFilesystemPreopens020 from './interfaces/wasi-filesystem-preopens.js'; // import wasi:filesystem/preopens@0.2.0
export type * as WasiFilesystemTypes020 from './interfaces/wasi-filesystem-types.js'; // import wasi:filesystem/types@0.2.0
export type * as WasiIoError020 from './interfaces/wasi-io-error.js'; // import wasi:io/error@0.2.0
export type * as WasiIoPoll020 from './interfaces/wasi-io-poll.js'; // import wasi:io/poll@0.2.0
export type * as WasiIoStreams020 from './interfaces/wasi-io-streams.js'; // import wasi:io/streams@0.2.0
export type * as WasiRandomInsecureSeed020 from './interfaces/wasi-random-insecure-seed.js'; // import wasi:random/insecure-seed@0.2.0
export type * as WasiRandomInsecure020 from './interfaces/wasi-random-insecure.js'; // import wasi:random/insecure@0.2.0
export type * as WasiRandomRandom020 from './interfaces/wasi-random-random.js'; // import wasi:random/random@0.2.0
export type * as WasiSocketsInstanceNetwork020 from './interfaces/wasi-sockets-instance-network.js'; // import wasi:sockets/instance-network@0.2.0
export type * as WasiSocketsIpNameLookup020 from './interfaces/wasi-sockets-ip-name-lookup.js'; // import wasi:sockets/ip-name-lookup@0.2.0
export type * as WasiSocketsNetwork020 from './interfaces/wasi-sockets-network.js'; // import wasi:sockets/network@0.2.0
export type * as WasiSocketsTcpCreateSocket020 from './interfaces/wasi-sockets-tcp-create-socket.js'; // import wasi:sockets/tcp-create-socket@0.2.0
export type * as WasiSocketsTcp020 from './interfaces/wasi-sockets-tcp.js'; // import wasi:sockets/tcp@0.2.0
export type * as WasiSocketsUdpCreateSocket020 from './interfaces/wasi-sockets-udp-create-socket.js'; // import wasi:sockets/udp-create-socket@0.2.0
export type * as WasiSocketsUdp020 from './interfaces/wasi-sockets-udp.js'; // import wasi:sockets/udp@0.2.0
export * as iterTpl from './interfaces/iter-tpl-main-iter-tpl.js'; // export iter-tpl:main/iter-tpl@0.0.1
