package iter-tpl:tpl@0.0.1;

interface template {
    execute: func(tpl: string, array: list<string>) -> result<string, string>;
}

world tpl {
    include wasi:cli/imports@0.2.0;

    export template;
}
